#cloud-config

package_update: true
package_upgrade: false

packages:
  - git
  - curl
  - make
  - ca-certificates
  - net-tools
  - python3-pip
  - python3-venv

runcmd:
  - ufw allow 5001
  - ufw allow 9001
  - git clone https://github.com/leetschau/mlflow-setup.git /mlflow-setup
  - cd /mlflow-setup && cp docker/.env.example docker/.env && make all
